sudo: required

language: python

services:
  - docker

before_install:
  - docker build -t syntaxnet_wrapper_test .

script:
  - docker run syntaxnet_wrapper_test /bin/bash -c "cd /root/syntaxnet-wrapper && python -m unittest discover ."
